languaje: node_js #programming languaje
node_js: #node --version 
  - "8" 
dist: trusty #VM SO
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script:
  - nohup npm run start & #Run this process in background (&) and no matter if the shell is closed still continue running that process (nohup)
  - sleep 3
  - npm run test

